### ISSUE TITLE
[Fluid Drawers Legacy-1.16.5-forge-1.0] Hidden Hwyla depencie 

### ISSUE THREAD

**Issue by PokeMaserJ** [joe-vettek/Fluid-Drawers-Legacy#1]
Without Hwyla , Minecraft will crash. 

https://gist.github.com/PokeMaserJ/0f37359ed036c366918aa465055e447c

**Comment by joe-vettek** [comment]
It's ok now.

**Comment by joe-vettek** [comment]
You can test 1.0.3 again which is on curseforge. Thank you for letting me knowing this.

**Comment by PokeMaserJ** [comment]
Doesn't crash anymore.
