### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DragonMaster14545** [joe-vettek/Fluid-Drawers-Legacy#11]
## Game Version, Launcher Version, Mod Version

MC 1.18.2

Forge 40.2

Fluid Drawers Legacy newest

## Problem Description

My server crashed suddenly, but I didnt do anything, noone was online

## Crash Log

https://pastebin.com/CMB2zHNk

**Comment by joe-vettek** [comment]
I think I may get the answer but I'm not sure about it .
Could you take a screenshot of your game about the situation of your drawers?

**Comment by DragonMaster14545** [comment]
Ill do that as soon as i come home, but its connected to my big storage drawer warehouse

**Comment by joe-vettek** [comment]
nothing, I just want to see if the drawer controller is being pumped while being poured

**Comment by DragonMaster14545** [comment]
There are some slaves, fluids and items beeing pumped in, but not pumped out at the time

**Comment by joe-vettek** [comment]
Then it seems that the problem should be here, you did not extract the fluid, but the error message told me that there was fluid being extracted at that time.
So it could actually be wrong pipe placement that's causing this, anyway, I'm going to start by making this problem as broad as possible.

**Comment by DragonMaster14545** [comment]
![image](https://user-images.githubusercontent.com/114180377/214592905-9ccc05de-fd69-4f72-b6d9-df42d6c9aa2a.png)
![image](https://user-images.githubusercontent.com/114180377/214593084-1c327f69-26e4-4cc0-8d7e-e67d9f266e86.png)
Im sorry I forgot Im actually pulling out something here, but the tanks are full since ages

**Comment by joe-vettek** [comment]
A beta version has been released.

**Comment by DragonMaster14545** [comment]
Thanks a lot for the quick fix
