### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by ghost** [joe-vettek/Fluid-Drawers-Legacy#13]
## Game Version, Launcher Version, Mod Version

MC 1.16.5

Forge 36.2.34

Fluid Drawers Legacy 1.2.0

## Problem Description

When placing a tank, the item is removed from the inventory correctly but when sorting inventory afterwards or opening any block with a UI all the tanks placed pop back into the slot you placed them from essentially duplicating all the drawers placed. This only seems to be an issue when the tanks are crafted and stacked in inventory. cheating on in while in creative mode and placing in survival mode has the intended effect. and breaking and placing a tank that is already placed in the world also has intended effect.

## Crash Log

Game does not crash.

**Comment by joe-vettek** [comment]
sorting? Please only test with this mod and pre-mods, the sorting mods are prone to duplication problems, and my single-person test is no problem.

**Comment by joe-vettek** [comment]
![image](https://user-images.githubusercontent.com/82761814/219408878-882c90e0-382b-4576-b0f7-70e520920fbb.png)

**Comment by joe-vettek** [comment]
Also sorry because I'm busy so it might take a while to change the code even if the issue is confirmed. But at the moment I can't see how this has anything to do with my mod.

**Comment by ghost** [comment]
Couldn’t tell you. But I was able to fix the issue by changing the recipe with craft tweaked to create the tank with NBT for Minecraft:empty. And the issue is no longer present.

**Comment by joe-vettek** [comment]
Glad to see you solved the problem.
The current version actually in the build is 1.18.2. Of course, this does not mean that the old version has lost maintenance, but switching versions is indeed a troublesome thing, which means rebuilding. This is not very friendly to my region. When the network is bad, the build time usually exceeds half an hour or even longer, so when there is a problem with the old version, I have to wait until I have enough time to solve it.
I'll close the question then.
