### ISSUE TITLE
Using bucket of fluid on locked, empty drawer deletes the fluid

### ISSUE THREAD

**Issue by mtbrenner** [joe-vettek/Fluid-Drawers-Legacy#14]
## Game Version, Launcher Version, Mod Version

MC 1.18.2

Forge 40.1.80

Fluid Drawers Legacy 2.3.5

## Problem Description

Pack is Caveopolis 4.3. To reproduce:
- place an empty fluid drawer
- put 1 bucket of water in it
- lock it
- remove the water with bucket - visually there is still water in it but the bucket is empty
- use a bucket of lava on it
Result: the lava is lost and an empty bucket is returned.

## Crash Log

[paste link here]

**Comment by joe-vettek** [comment]
Thank you so much for bringing this up, it was an oversight in testing. This issue exists in survival mode, but behaves fine in creative mode.

**Comment by joe-vettek** [comment]
![image](https://user-images.githubusercontent.com/82761814/221848664-acc7e98a-fc72-4cc1-9870-d08356fee3f0.png)
 repair it
