### ISSUE TITLE
1.19.4 it makes my game !crash down!

### ISSUE THREAD

**Issue by AliceLeader** [joe-vettek/Fluid-Drawers-Legacy#16]
## Game Version, Launcher Version, Mod Version

MC 1.19.4

Forge 45.2.4

Fluid Drawers Legacy 3.2.1-beta

## Problem Description

 when i shift+right click the drawer ,my game crash and i can't pull in by my bucket

## Crash Log

[debug-1.log.gz](https://github.com/joe-vettek/Fluid-Drawers-Legacy/files/13265407/debug-1.log.gz)

**Comment by joe-vettek** [comment]
log prompts me that it seems to be caused by the fact that the fulid texture can't be found. What fluid you poured?

**Comment by joe-vettek** [comment]
Try pouring water into the corresponding game version and almost everything works fine.
By the way, 1.19 is not a stably supported version. It is recommended to play 1.20.

**Comment by joe-vettek** [comment]
Supplement: After version 1.19.3, Minecraft no longer provides texture supplement support for air fluids.
