### ISSUE TITLE
Issue with Drawer Controllers and Drawer Controller Slaves

### ISSUE THREAD

**Issue by mcm** [joe-vettek/Fluid-Drawers-Legacy#17]
## Game Version, Launcher Version, Mod Version

MC 1.20.1

Forge 47.2.0

Fluid Drawers Legacy 4.1.3-release

## Problem Description

Drawer contents don't drain when fluids are pulled from a drawer controller or a drawer controller slave. When a pump is used to pull directly from the drawer, the contents drain as expected. Fluids can be pumped into both drawer controllers and drawer controller slaves. But when a pump is connected to either a drawer controller or a drawer controller slave, the contents of the fluid drawer don't change.

**Comment by joe-vettek** [comment]
you mean controller or controller slave don't change the fluid in the drawers which is belong to them? let me check it.

**Comment by joe-vettek** [comment]
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/268fb079-c7a9-41cf-99ab-1591ecf635ee)
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/b091fb07-6ec3-42c7-a0c3-b2891d19a59b)
the cable in Cyclic works. which mod are you using?

**Comment by mcm** [comment]
Ahhh should've specified! I'm using pipes from the Create mod, and yes - if I pump away from the drawer controller, the level of fluid goes up in the tank but doesn't go down in the drawer.

**Comment by mcm** [comment]
Added screenshots of what works (direct to the drawer) and what doesn't (pulling from the controller). With the controller, the tank will just keep filling and the drawer will stay at 1B

![2024-02-11_22 02 26](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/4228826/ce7794bc-821e-4383-b487-a8764cf8e055)
![2024-02-11_22 02 36](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/4228826/48f9135c-db6e-4410-91d2-c850f8fd18c0)

**Comment by joe-vettek** [comment]
umm, i think it may be the problem from Create

**Comment by joe-vettek** [comment]
I'll double check.

**Comment by joe-vettek** [comment]
![image](https://github.com/joe-vettek/Fluid-Drawers-Legacy/assets/82761814/927b2596-d2d3-445d-aee1-1dfd07ae3fa3)
This problem is somewhat special. Create uses a special method to extract fluid, and the code happened to produce an incorrect variable pointer during a certain update. It doesn't crash the game and is used less often, which I think is why this issue has gone undetected.
Thank you very much for identifying this issue, a fix will be released at a later date.

**Comment by joe-vettek** [comment]
The file has been uploaded to Curseforge, it will take about a few dozen minutes.

**Comment by mcm** [comment]
Just updated and confirmed it's working as expected. Thanks so much!
