### ISSUE TITLE
Error with latest Storage Drawers update (1.18.2)

### ISSUE THREAD

**Issue by spoonypanda** [joe-vettek/Fluid-Drawers-Legacy#19]
## Game Version, Launcher Version, Mod Version

MC 1.18.2

Forge 40.2.21

Fluid Drawers Legacy 1.18.2-forge-2.3.9

## Problem Description

It looks like Storage Drawers add-on may have changed how the classes are accessed. Trying to troubleshoot another mod, I've updated to the latest storage drawers version for 1.18.2 (Storage Drawers 10.3.0) https://www.curseforge.com/minecraft/mc-mods/storage-drawers/files/5636643 and this causes Fluid drawers to crash with the error I linked below.

## Crash Log

https://pastebin.com/eiQkQSSX

**Comment by joe-vettek** [comment]
You are using the outdated Fluid Drawers Legacy version first.
Secondly, this thing does exist, and I personally think it is not necessary to use the latest Storage Drawers version.
Furthermore, I am more opposed to changing the class name of old mod at will. Not every developer has the time to maintain an old version of the development environment, especially after 1.20, the development environment is no longer Forge. **I think it is really not a good thing to change the class name that has been used committed for two years but not used.** I will tell jaquadro my opinion.
Finally, I don’t know how many people are still willing to use the new version I released. At least four months have passed and the download volume of 2.4.0 is less than 200.

**Comment by spoonypanda** [comment]
Honestly, I think you can blame some of that on how piss poor Curseforge is for listing mod versions -- I found the right one for that version after you mention it here, sorry about that!

And yeah -- about the other dev changing the class name, I'd agree, seems like bad practice -- I was more or less opening this to let you know. Thanks for the mod anyway :)

The whole reason why I even dove into this and found the bug is because an old version of every compat doesn't work for BoP like it should, but the fix is only compatible with the newest drawers version --- which has the change for that class name it seems. It's like playing tetris I swear!

Anyway, I won't lose any sleep if you don't do anything about it, I more or less just wanted to make you aware.

**Comment by joe-vettek** [comment]
I have reported this issue to the author of the Storage Drawers yesterday. He said that the latest version will be marked as beta and recommended that you use the old version, but I am not sure what will happen next.

Due to this uncertainty, emm, this change is mainly difficult to handle. I need to see the situation, because I am not sure whether the class name will be restored or not.

Thank you for the report.

**Comment by joe-vettek** [comment]
complete
