### ISSUE TITLE
Crash when shift right clicking

### ISSUE THREAD

**Issue by Coldcolor900** [joe-vettek/Fluid-Drawers-Legacy#20]
## Game Version, Launcher Version, Mod Version

MC 1.20.1

Forge 47.3.0

Fluid Drawers Legacy 5.0.1

## Problem Description

Basically title. I tried shift right clicking a drawer with liquid xp from Create Enchantment Industry, and the game crashed.

## Crash Log

https://cfpaste.modularity.gg/paste/?content=525819185712988180_1296938524691529820&filename=crash-2024-10-18_14.39.59-client.txt

**Comment by joe-vettek** [comment]
i see your storage drawers version is very high with 12.7. the mod is upgraded when SD is 12.0.2.
so you can try older version of SD.
i am busy with something else those days, so it may cost some time for me to fix it.
SD suddenly had a lot of code updates after being silent for a while, which caused a lot of problems.

**Comment by joe-vettek** [comment]
test it with latest StorageDrawers-1.20.1-12.9.11 and not crash.  

![image](https://github.com/user-attachments/assets/13c61c8e-7e00-4608-98a1-3ef65cdcc6e1)
