### ISSUE TITLE
Neoforge won't load this

### ISSUE THREAD

**Issue by Leichenengel** [joe-vettek/Fluid-Drawers-Legacy#21]
**MC-Version** 1.21.1,
**JavaLauncher** v.3.5.17-2.1.3
**FluidDrawersLegacy**-1.21-neoforge-6.0.1.jar

Hello there :)

I wanted to expand my Storage Drawers Network with Fluid Storage and Texelsaur was so nice to post a link to your mod on their SD-Profile on curseforge. So I downloaded the latest version for neoforge, checked for additional dependencies and then tried to load minecraft. This is what happened:

![errormsg-fluiddrawers-neoforge](https://github.com/user-attachments/assets/dea7f33c-1983-4765-b320-6d1386c29a99)

This is the log I got when I clicked on the "Go to Logfile"-button on the error screen.

[latest-log-after-loading-error.log](https://github.com/user-attachments/files/18039679/latest-log-after-loading-error.log)

If you nee additional info, please let me know :)

Cheers!

**Comment by joe-vettek** [comment]
maybe you can try a old verision of storage drawers at now. i need some time to update it.

**Comment by joe-vettek** [comment]
Storage Drawers was recently ported to a new platform and many things have changed.
