### ISSUE TITLE
Crash on the latest StorageDrawers-1.18.2-10.2.1

### ISSUE THREAD

**Issue by xuwuwudi** [joe-vettek/Fluid-Drawers-Legacy#3]
## Game Version, Launcher Version, Mod Version

MC 1.18.2

Forge 40.1.25

FluidDrawersLegacy-1.18.2-forge-2.0.1-universal

## Problem Description

crash

## Crash Log

[crash-2022-05-28_14.22.20-client.txt](https://github.com/joe-vettek/Fluid-Drawers-Legacy/files/8790637/crash-2022-05-28_14.22.20-client.txt)

**Comment by joe-vettek** [comment]
Because there is an announcement to change the code structure, errors are inevitable. Please use a version lower than 10.2.1 or not updated in the last few days.

**Comment by joe-vettek** [comment]
This issue will be fixed next week at the latest.

**Comment by joe-vettek** [comment]
ok
