### ISSUE TITLE
Fluid Drawers causes a crash with latest update from storage drawers and few other mods.

### ISSUE THREAD

**Issue by coaber** [joe-vettek/Fluid-Drawers-Legacy#4]
## Game Version, Launcher Version, Mod Version

MC 1.18.2

Forge 40.1.25

Fluid Drawers Legacy 2.0.1

## Problem Description

After updating storage drawers, architectury, crafttweaker, crash utillities, kubejs and sophisticated storage, game would crash upon interaction with anything. in crash logs it appears fluid drawers seem to be the cause, but could be wrong.

## Crash Log

[crash-2022-05-29_05.45.27-client.txt](https://github.com/joe-vettek/Fluid-Drawers-Legacy/files/8792543/crash-2022-05-29_05.45.27-client.txt)

**Comment by joe-vettek** [comment]
it's the same with #3
