### ISSUE TITLE
Locked, empty drawers still accept incoming liquids.

### ISSUE THREAD

**Issue by BonaireDreams** [joe-vettek/Fluid-Drawers-Legacy#5]
## Game Version, Launcher Version, Mod Version
MC 1.18.2
Forge 40.1.30
Fluid Drawers Legacy 2.1.0

## Problem Description
Locked, yet empty fluid drawers will accept any liquid entering the drawer controller they are attached to.

Expectation: Like storage drawers, a locked fluid drawer should not accept any liquid even if empty.

**Comment by joe-vettek** [comment]
that's strange. I'll check it

**Comment by joe-vettek** [comment]
Thanks for mentioning this old question, I didn't find out the reason for the loss of lock until today. I will upload a new version in a while. It is worth mentioning that I changed the texture model by the way, so it will take a long time.

**Comment by shiftthedev** [comment]
I created 2 pull requests (one for each version) that fixes this issue.
hope it helps.

thx for the mod.

**Comment by joe-vettek** [comment]
thanks iamshift' efffort. I was busy in the last six months so that can't deal with the issue.

**Comment by joe-vettek** [comment]
But the problem still occur there due to the lock mechanism of StorageDrawer and my misunderstandings.
And Now I think I have came nearly by the truth.

**Comment by joe-vettek** [comment]
I have known the problem before the issue with the help of a kind player in the Discord channel of StorageDrawer. But when I solved this problem, another problem came out.
**So the drawer is locked, it's actually an illusion.**
I may sound like I'm speaking in a riddle, but that's what it is.

**Comment by joe-vettek** [comment]
For the player, there is a way to make the drawer enter a special state. It's locked, but it's not locked. In-game it appears as a constant lock (doesn't respond to using a key for it, or flashes past it), and it's the same during NBT's inspection process.

**Comment by joe-vettek** [comment]
But in fact the key is valid, but I can't find a better way to find out the truth for the time being.
So actually, it just looks like it's locked, it's not. **Of course, if you right-click once with the key, you can actually lock it.** This is the answer.
It will take a while for me to continue working on it, and can't fix it just yet. But I have to explain the situation in advance.

**Comment by joe-vettek** [comment]
A relatively simple solution is to reposition the drawer once.

**Comment by joe-vettek** [comment]
It will be fixed in the next release.
